airbnb:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"

      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"

      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 4
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
  target: dev
